export const users = [
  {
    id: 1,
    name: "ธนพล ร่ำรวย",
    zodiac: "สิงห์",
    lineId: "Urpmdnlhvtlk...",
    status: "complete",
    questions: 20,
    lastActive: "ประมาณ 11 ชั่วโมงที่ผ่านมา",
  },
  {
    id: 2,
    name: "ประเสริฐ มั่นคง",
    zodiac: "-",
    lineId: "U7wr6cxxn1qn...",
    status: "incomplete",
    questions: 16,
    lastActive: "ประมาณ 12 ชั่วโมงที่ผ่านมา",
  },
  {
    id: 3,
    name: "สมหญิง รักดี",
    zodiac: "มกร",
    lineId: "Umkm32waw8...",
    status: "complete",
    questions: 32,
    lastActive: "ประมาณ 15 ชั่วโมงที่ผ่านมา",
  },
  {
    id: 4,
    name: "นิรันดร์ เจริญ",
    zodiac: "-",
    lineId: "U679m83n9qf...",
    status: "incomplete",
    questions: 24,
    lastActive: "ประมาณ 15 ชั่วโมงที่ผ่านมา",
  },
  {
    id: 5,
    name: "วิชัย สุขสันต์",
    zodiac: "เมถุน",
    lineId: "U0vtk6ll0xpd...",
    status: "complete",
    questions: 10,
    lastActive: "ประมาณ 16 ชั่วโมงที่ผ่านมา",
  },
  {
    id: 6,
    name: "วิชัย สุขสันต์",
    zodiac: "-",
    lineId: "Usxcmir0w7vc...",
    status: "incomplete",
    questions: 3,
    lastActive: "ประมาณ 17 ชั่วโมงที่ผ่านมา",
  },
  {
    id: 7,
    name: "วิชัย สุขสันต์",
    zodiac: "กุมภ์",
    lineId: "Uldcc6ddfs2f...",
    status: "complete",
    questions: 44,
    lastActive: "ประมาณ 23 ชั่วโมงที่ผ่านมา",
  },
]
