# Generated by Django 5.2.13 on 2026-04-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZodiacKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
